### ISSUE TITLE
editing password on permission is impossible

### ISSUE THREAD

**Issue by individual-it** [owncloud/libre-graph-api#136]
Neither `Permission` nor `SharingLink` has a password property, there is no need to be able to read the password, but there should be a way to update/change a password for a link.

`Permission` only has `hasPassword` so e.g. in the PHP code we can use
`public function setHasPassword(?bool $has_password): static`
but there is no way to set a new password

**Comment by micbar** [comment]
Checked the behavior of OneDrive:

1.  They are using `POST https://graph.microsoft.com/beta/drives/78186EAC57577F04/items/78186EAC57577F04!308/createLink` again and set the password there
2. They only have one link per resource.

**Comment by micbar** [comment]
@butonic @individual-it 

I think we could add a `/v1beta1/drives/{drive-id}/items/{item-id}/permissions/{perm-id}/password/`
