### ISSUE TITLE
no way to enable a disabled drive again

### ISSUE THREAD

**Issue by individual-it** [owncloud/libre-graph-api#148]
I cannot see a way to do that

**Comment by amrita-shrestha** [comment]
@individual-it is this still valid?

**Comment by phil-davis** [comment]
https://github.com/owncloud/ocis-php-sdk/blob/main/tests/integration/Owncloud/OcisPhpSdk/DriveTest.php
has:
```
    public function testEnableDrive(): void
    {
        $this->drive->disable();
        $this->drive->enable();
        $this->assertFalse($this->drive->isDisabled(), "Failed to enable the drive ".$this->drive->getName());
    }
```
and the test passes.
So a way to enable a disabled drive has been found.
