### ISSUE TITLE
Difference between drive.createdBy and drive.createdByUser?

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/libre-graph-api#25]
The schema for `drive` describes `createdBy` and `createdByUser` as follows:
- `createdBy`: `identitySet`, `Identity of the user, device, or application which created the item. Read-only.`
- `createdByUser` : `user`, Identity of the user who created the item. Read-only.`

The information here seems to be redundant, as the meaning is described as the same and `identitySet` can also store a `user`. Why does `drive.createdByUser` exist and when should it be used?

**Comment by butonic** [comment]
`createdByUser` does not exist on the graph api, it should be removed from the libregraph.

**Comment by rhafer** [comment]
> `createdByUser` does not exist on the graph api, it should be removed from libregraph.

Agreed. And since we're neither using ` createdBy` nor `createdByUser` anywhere in the  server yet. I think it's save to just remove `createdByUser` from the spec. The same is btw true for `lastModifiedByUser` vs `lastModifiedBy`.
