### ISSUE TITLE
can we generate code with uppercase abbreviations for ID and URL

### ISSUE THREAD

**Issue by butonic** [owncloud/libre-graph-api#4]
../../../graph/pkg/service/v0/drives.go:215:5: unknown field 'Id' in struct literal of type msgraph.Entity (but does have ID)
../../../graph/pkg/service/v0/drives.go:223:5: unknown field 'Id' in struct literal of type msgraph.Identity (but does have ID)
../../../graph/pkg/service/v0/drives.go:232:6: unknown field 'Id' in struct literal of type msgraph.Entity (but does have ID)
../../../graph/pkg/service/v0/drives.go:243:13: drive.Root.WebDavUrl undefined (type *msgraph.DriveItem has no field or method WebDavUrl, but does have WebDavURL)

**Comment by micbar** [comment]
This was an incompatibility between our spec and yeakeshi.

Golang convention is camelCase

**Comment by micbar** [comment]
https://github.com/owncloud/libre-graph-api-go/blob/main/model_drive.go#L21
