### ISSUE TITLE
permissions grantedTo should be a single identitySet

### ISSUE THREAD

**Issue by butonic** [owncloud/libre-graph-api#68]
we should have used `grantedToIdentities`, which is a collection
https://learn.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0

Since this is a breaking change we should 
1. add the `grantedToIdentitiesV2` collection
2. make all clients use that instead of `grantedTo`
3. correct `grantedTo`

`grantedToIdentities` and `grantedTo` have been marked as deprecated in msgraph ... in favor of `grantedToV2` and `grantedToIdentitiesV2`, which use a [SharePointIdentitySet](https://learn.microsoft.com/en-us/graph/api/resources/sharepointidentityset?view=graph-rest-1.0) instead of an [IdentitySet](https://learn.microsoft.com/en-us/graph/api/resources/identityset?view=graph-rest-1.0). The biggest difference is that the `sharePointIdentitySet` also carries a `group` property to allow associating groups with actions.

**Comment by micbar** [comment]
Quick Fix:

- Rename `grantedTo` into `grantedToIdentities`.

@fschade will take care

**Comment by micbar** [comment]
Fixed by https://github.com/owncloud/libre-graph-api/pull/74
